layers:
  - name: "food"
    title: "Restaurant and fast-food"
    minZoom: 5
    maxZoom: 19
    filter:
      $or: 
      - 'properties.tags.amenity': 'restaurant'
      - 'properties.tags.amenity': 'fast_food'
  - name: "bar"
    title: "Bar, cafe, pub, ..."
    minZoom: 5
    maxZoom: 19
    filter:
      $or: 
      - 'properties.tags.amenity': 'bar'
      - 'properties.tags.amenity': 'pub'
      - 'properties.tags.amenity': 'cafe'
      - 'properties.tags.amenity': 'biergarten'
      - 'properties.tags.amenity': 'nightclub'
  - name: "hotel"
    title: "Hotels"
    minZoom: 5
    maxZoom: 19
    filter:
      "properties.tags.tourism": "hotel"
  - name: "playground"
    title: "Playground"
    minZoom: 5
    maxZoom: 19
    filter:
      "properties.tags.leisure": "playground"
  - name: "artwork"
    title: "Art work"
    minZoom: 5
    maxZoom: 19
    filter:
      "properties.tags.tourism": "artwork"
  - name: "toilets"
    title: "Toilets"
    minZoom: 5
    maxZoom: 19
    filter:
      'properties.tags.amenity': 'toilets'
  - name: "charging"
    title: "Charging station"
    minZoom: 5
    maxZoom: 19
    filter:
      'properties.tags.amenity': 'charging_station'
  - name: "trees"
    title: "Trees"
    minZoom: 9
    maxZoom: 19
    filter:
      'properties.tags.natural': 'tree'
  - name: "wind"
    title: "Wind turbines"
    minZoom: 4
    maxZoom: 19
    filter:
      'properties.tags.generator:source': 'wind'
  - name: "nuclear"
    title: "Nuclear reactors"
    minZoom: 1
    maxZoom: 19
    filter:
      'properties.tags.generator:source': 'nuclear'